image: cr.yandex/crp742p3qacifd2hcon2/practice-da:latest

stages:
    - init
    - run

test_report_job:
    stage: run
    only:
        refs:
        - schedules
        variables:
        - $SCHEDULE_TYPE == "daily_report"
    script:
        - python report.py

test_report_job2:
    stage: run
    only:
        refs:
        - schedules
        variables:
        - $SCHEDULE_TYPE == "daily_report"
    script:
        - python report2.py

alert_report_job:
    stage: run
    only:
        refs:
        - schedules
        variables:
        - $SCHEDULE_TYPE == "alert_report"
    script:
        - python alert_report.py

